In [2]:
! pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip


In [13]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
arr1.shape

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


(6,)

In [15]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]])
print(arr2)
arr2.shape


[[1 2 3 4]
 [2 3 4 5]]


(2, 4)