In [6]:
! pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip


In [7]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
arr1.shape

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


(6,)

In [8]:
arr2 = np.array([[1,2,3,4],[2,3,4,5]])
arr3 = np.array([6,7,8,9,2,3])
print(arr2)
arr2.shape


[[1 2 3 4]
 [2 3 4 5]]


(2, 4)

In [9]:
print(arr1+arr3)
print(arr1/arr3)
print(arr1*arr3)

[ 7  9 11 13  7  9]
[0.16666667 0.28571429 0.375      0.44444444 2.5        2.        ]
[ 6 14 24 36 10 18]


In [10]:
are = np.array([[1,2,[21,22,35],3,4,5],[44,33,22,11],[11,22,33,44]], dtype=object)

In [16]:
are[0][2][1]

22